version: '3'
services:

  web:
    image: nginx:1.19
    restart: unless-stopped
    volumes:
      - ../app/public:/var/www
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80

  build:
    image: node:12
    working_dir: /app
    volumes:
      - ../app:/app
    ports:
      - 5757:5757

  lambda:
    build:
      context: ../
      dockerfile: docker/lambda.Dockerfile
    env_file: ../.lambda.env
    volumes:
      - ../src:/var/task

  python-cli:
    build:
      context: ../
      dockerfile: docker/python-cli.Dockerfile
    env_file: ../.lambda.env
    volumes:
      - ../scripts/util/local-secrets-loader.py:/usr/src/util/local-secrets-loader.py

  awslocal:
    image: localstack/localstack
    restart: unless-stopped
    environment:
      - SERVICES=secretsmanager,dynamodb
      - DEFAULT_REGION=eu-west-1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    ports:
      - 4566:4566
