version: '3'
services:

  web:
    image: nginx:1.19
    restart: unless-stopped
    volumes:
      - ../app/public:/var/www
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80

  build:
    image: node:14
    working_dir: /app
    volumes:
      - ../app:/app
    ports:
      - 5757:5757
