#!/usr/bin/env bash

# Purpose:
#
# Runs a command inside the build container.

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

if [ $1 == "build" ]; then
    docker-compose run --service-ports --rm build npm run build

elif [ $1 == "watch" ]; then
    docker-compose run --service-ports --rm build npm run watch

else
    docker-compose run --service-ports --rm build $@
fi
