#!/usr/bin/env bash

# Purpose:
#
# Runs a command inside the build container.

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

if [ $1 == "dev" ]; then
    docker-compose run --service-ports --rm build npx mix

elif [ $1 == "prod" ]; then
    docker-compose run --service-ports --rm build npx mix --production

elif [ $1 == "watch" ]; then
    docker-compose run --service-ports --rm build npx mix watch

else
    docker-compose run --service-ports --rm build $@

fi
