#!/usr/bin/env bash

# Purpose:
#
# Runs a command inside the build container.

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

# Pass any arguments as command into the build container 
docker-compose run --service-ports --rm build $@
