#!/usr/bin/env bash

# Purpose:
#
# Hydrates local instance of secrets manager
#  with secrets.json file

# Location of secrets json file
SECRET_FILE="secrets.json"

# Bash colour variables
COLOUR_GREEN="\x1b[32;01m"
COLOUR_RED="\x1b[31;01m"
COLOUR_RESET="\x1b[39;49;00m"

cd "$(dirname "$0")/.."

echo -e "--> "$COLOUR_GREEN"Hydrating local AWS Secrets Manager"$COLOUR_RESET

if [ ! -f $SECRET_FILE ]; then
    echo -e "$SECRET_FILE --> "$COLOUR_RED"secret file was not found"$COLOUR_RESET
    echo -e "Create the file, and try again"
    exit 1
fi

docker-compose run \
    --rm \
    --workdir="/usr/src/sl" \
    python-cli \
    python local-secrets-loader.py < $SECRET_FILE

echo ""
